C:\Users\meteh\anaconda3\Lib\site-packages\google\protobuf\internal\well_known_types.py:174: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

Exception in thread Thread-15 (start_federated_client):
Traceback (most recent call last):
  File "C:\Users\meteh\anaconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\meteh\anaconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\meteh\OneDrive\Desktop\federated_learning_hospital_data\app.py", line 266, in start_federated_client
    fl.client.start_numpy_client(server_address="localhost:8080", client=client)
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 731, in start_numpy_client
    start_client(
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 201, in start_client
    start_client_internal(
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 438, in start_client_internal
    message = receive()
              ^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\grpc_client\connection.py", line 142, in receive
    proto = next(server_message_iterator)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\grpc\_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\grpc\_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:8080: ConnectEx: Connection refused (No connection could be made because the target machine actively refused it.
 -- 10061)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-04-15T22:24:20.5281849+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:8080: ConnectEx: Connection refused (No connection could be made because the target machine actively refused it.\r\n -- 10061)"}"
>
